import '../globals.css'
import Navbar from '@/components/features/header/navigation/navbar'
import Footer from '@/components/features/footer'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        <main className="max-w-7xl mx-auto">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
